before_install:
  - openssl aes-256-cbc -K $encrypted_45757fbb12c0_key -iv $encrypted_45757fbb12c0_iv -in id_rsa.travis.enc -out id_rsa.travis -d 
  - ls -la id_rsa.travis
  
install:
  - sudo pip install -r requirements.txt
  
script:
  - python __testbuild.py digitalocean --api_token $do_api_v2_token

after_script:
  - rm id_rsa.travis
