sudo: true
language: python
python:
- 2.7

env:
  global:
  - secure: kDAI818hwV0MF87EI0PANbIsX/AIiNrsI0+hdiOd4bmH7VGM71/qjaaoZVyDmfkkEvA/qrn4LUuH3YQ7VTtrgZm/ggDLxi03XIvJwez9knSc9x/XLdd/Xj/Q36KYrccuZwJsDUAtjiL6oWp84wbuvESeuFdp9ufn5mSMRAcaQbIdYudxGbU7AQrP0CC5huJvF8aoaIZFwhV2d+n9YLqxpZ9Etax5BV+cWAu9AXGu+gt4xF1dKcYxqsdSvUahrq8Z2IbCcy/KSBbZLjmwP8ze4nFl0yocW++sNqr0oEa0KNBEgwO6vvolmkPm93dz7AewMxkWSeDFCSZKHmZWuqVVllUuJfKOUOeF18NjYSKUayuHzml7CBQZgMBjPYdaa8jIgp/uHwMwPYYP/a6zSkevZ0Dqkq/qREF3NCVXs8BLgM8c9XcI1r6D9U80sMVj4829/tEikK9QqO6W0Q7qf0+V9j48PR5qZXbIthj+pon7Q6k3dNUvaAKWOalOT5IS5bBp9gLrGDakhnB+iRTZ8MnFXMT59XI9pvTsoFYxBsWcY0zTaxiivKJ25eCeESNVnqBWR01/TotsdeIcyF9dbsAT/hmp8hMtmi009eIPdVkyMoKHQXEYN3z4B7Ux11clVLDIsY9BX91XVaagXKEUppaIadlEnRb5heZRzXBENgRa/XI=

addons:
  artifacts:
    s3_region: us-west-2
    paths:
    - $(ls tests/artifacts/*.png | tr "\n" ":")

cache:
  directories:
  - "$HOME/.cache/pip"

before_cache:
- rm -f $HOME/.cache/pip/log/debug.log

before_install:
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && openssl aes-256-cbc -K $encrypted_45757fbb12c0_key
  -iv $encrypted_45757fbb12c0_iv -in id_rsa.travis.enc -out id_rsa.travis -d || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && export CHROME_BIN=/usr/bin/google-chrome || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && export DISPLAY=:99.0 || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/netflix-proxy_xvfb_99.pid
  --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo apt-get update || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo apt-get install -y libappindicator1 fonts-liberation || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo dpkg -i google-chrome*.deb || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo apt-get install build-essential python-dev libffi-dev libssl-dev || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo -H pip install --upgrade cryptography || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo -H pip install --upgrade pyopenssl ndg-httpsclient pyasn1 || false'

install:
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo -H pip install -r tests/requirements.txt || false'

before_script:
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && chmod 600 id_rsa.travis && chmod 644 id_rsa.travis.pub || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && export NAME=$(uuidgen) || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && export RESOLVER=$(grep nameserver /etc/resolv.conf) || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo python tests/testbuild.py digitalocean --create --name ${NAME} --api_token=$do_api_v2_token
  --branch=$TRAVIS_BRANCH --region=$do_region --tb_user=$he_tunnel_broker_uname --tb_passwd=$he_tunnel_broker_passwd
  --tb_key=$he_tunnel_update_key --tb_index=$he_tunnel_index || sudo python tests/testbuild.py
  digitalocean --destroy --name ${NAME} --api_token=$do_api_v2_token || false'

script:
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo python tests/testvideo.py netflix --email=$netflix_email --password=$netflix_passwd || false'

after_script:
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && printf "${RESOLVER}\n" | sudo tee /etc/resolv.conf || false'
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo python tests/testbuild.py digitalocean --destroy --name ${NAME} --api_token=$do_api_v2_token || false'

after_success:
- '[ "${TRAVIS_REPO_SLUG}" = "${GH_REPO}" ] && sudo tests/gh-pages-push.sh || false'
