language: python

python:
  - 2.7

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
      - $(ls tests/artifacts/*.png | tr "\n" ":")

sudo: true

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - openssl aes-256-cbc -K $encrypted_45757fbb12c0_key -iv $encrypted_45757fbb12c0_iv -in id_rsa.travis.enc -out id_rsa.travis -d 
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0 
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/netflix-proxy_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - sudo apt-get install build-essential python-dev libffi-dev libssl-dev
  - sudo -H pip install --upgrade cryptography
  - sudo -H pip install --upgrade pyopenssl ndg-httpsclient pyasn1
  
install:
  - sudo -H pip install -r tests/requirements.txt

before_script:
  - chmod 600 id_rsa.travis && chmod 644 id_rsa.travis.pub
  - export NAME=$(uuidgen)
  - export RESOLVER=$(grep nameserver /etc/resolv.conf)
  - sudo python tests/testbuild.py digitalocean --create --name ${NAME} --api_token=$do_api_v2_token --branch=$TRAVIS_BRANCH --region=$do_region --tb_user=$he_tunnel_broker_uname --tb_passwd=$he_tunnel_broker_passwd --tb_key=$he_tunnel_update_key --tb_index=$he_tunnel_index || sudo python tests/testbuild.py digitalocean --destroy --name ${NAME} --api_token=$do_api_v2_token

script:
  - sudo python tests/testvideo.py netflix --email=$netflix_email --password=$netflix_passwd

after_script:
  - sudo python tests/testbuild.py digitalocean --destroy --name ${NAME} --api_token=$do_api_v2_token
  - printf "${RESOLVER}\n" | sudo tee /etc/resolv.conf
