reverse-proxy:
  image: abiosoft/caddy
  container_name: caddy
  ports:
    - "8080:80"
    - "4443:443"
  volumes:
    - ${BUILD_ROOT}/Caddyfile:/etc/Caddyfile
    - ${BUILD_ROOT}/wwwroot:/srv
    - ${HOME}/.caddy:/root/.caddy
  restart: always
